name: pass_gen_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  confirm_dialog: ^1.0.3
  connectivity_plus: ^5.0.2
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flex_color_picker: ^3.3.0
  flutter:
    sdk: flutter
  local_auth: ^2.1.7
  path_provider: ^2.1.1
  restart_app: ^1.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
